run:
	go build && DB_URI="mongodb://admin:foobar@localhost" DB_NAME="mydatabase" DB_COLL="mycoll" ./go-vs-js

test:
	DB_URI="mongodb://admin:foobar@localhost" DB_NAME="test_database" DB_COLL="test_coll" go test