# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mongo:
        image: mongo:4
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MONGO_INITDB_DATABASE: '${DB_DATABASE}'
        volumes:
            - .//volumes/mongodb/data:/data/db
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: '${DB_USERNAME}'
            ME_CONFIG_MONGODB_ADMINPASSWORD: '${DB_PASSWORD}'
        depends_on:
            - mongo
